name: artifact

on:
  push:
    branches:
      - main

jobs:
  build-file:
    runs-on: ubuntu-latest
    steps:
      - name: create the file 
        run: |
          echo "Build started at $(date)" > build.log
      
      - name: save artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

  use-aritfact:
    needs: build-file
    runs-on: ubuntu-latest
    steps:
      - name: print artifact
        uses: actions/download-artifact@v4
        with:
          name: build-log
      - name: print file
        run: cat build.log

