name: pr-check

on:
  pull_request:
    branches: [main]

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: print branch
        run: echo "This branch ':' ${{ git.ref_name }}"
