# workflow starts here 
name: pr-check

on:
  push:
    branches: [feature]

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: print branch
        run: echo "This branch ':' ${{ github.ref_name }}"
