name: read-secret

on:
  push:
    branches:
      - main

jobs:
  read-secret:
    runs-on: ubuntu-latest
    steps:
    env:
       MY_SECRET: ${{ secrets.MY_SECRET_MESSAGE  }}
      - name: Read and print secret
        run: echo "The secret is ${{ secrets.MY_SECRET }}"
